import Fastify from 'fastify';
import cors from '@fastify/cors';
import jwt from '@fastify/jwt';
import websocket from '@fastify/websocket';
import bcrypt from 'bcryptjs';
import {Aedes} from 'aedes';
import {createWebSocketStream} from 'ws';
import crypto from 'node:crypto';
import {EventEmitter} from 'node:events';
import nodemailer from 'nodemailer';
import {createServer as createTcpServer} from 'node:net';
import {z} from 'zod';
import {pool,migrate} from './db.js';
import {encrypt,decrypt,token} from './crypto.js';
import {allowedTopic,deviceTopic,parseTopic} from './topics.js';
import {executeWorkflow,Event,Definition} from './workflow.js';

const app=Fastify({logger:true,bodyLimit:1024*1024});
await app.register(cors, {
  origin: '*',
  methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization'],
}); await app.register(jwt,{secret:process.env.JWT_SECRET||'dev-only-change-this'}); await app.register(websocket,{options:{maxPayload:1024*1024,perMessageDeflate:true}});
const broker=await Aedes.createBroker({concurrency:100,drainTimeout:5000});
const bus=new EventEmitter(); const wsClients=new Map<string,Set<any>>(); const sseClients=new Map<string,Set<any>>();
const rate=new Map<string,{n:number,t:number}>();
function limited(ip:string){const now=Date.now();const x=rate.get(ip);if(!x||now-x.t>60000){rate.set(ip,{n:1,t:now});return false}x.n++;return x.n>300}
function emit(projectId:string,event:Event){bus.emit(projectId,event);for(const s of wsClients.get(projectId)||[])if(s.readyState===1)s.send(JSON.stringify({type:'event',event}));for(const r of sseClients.get(projectId)||[])r.raw.write(`event: ${event.type}\\ndata: ${JSON.stringify(event)}\\n\\n`)}
async function deviceByToken(t:string){const {rows}=await pool.query('SELECT d.*,p.name project_name FROM devices d JOIN projects p ON p.id=d.project_id WHERE d.token=$1',[t]);return rows[0]}
async function projectOwned(projectId:string,userId:string){const {rows}=await pool.query('SELECT id,name,api_key FROM projects WHERE id=$1 AND user_id=$2',[projectId,userId]);return rows[0]}
async function runWorkflows(event:Event){const {rows}=await pool.query('SELECT id,definition FROM workflows WHERE project_id=$1 AND enabled=true',[event.projectId]);for(const w of rows){const run=await pool.query('INSERT INTO workflow_runs(workflow_id,status,trigger_event) VALUES($1,$2,$3) RETURNING id',[w.id,'running',event]);try{await executeWorkflow(w.definition as Definition,event,{async 'action.telegram.send'(n,e){const c=await credential(w.definition.projectId||event.projectId,n.data?.credentialId,'telegram');if(!c)return;await fetch(`https://api.telegram.org/bot${c.token}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:c.chatId,text:render(n.data?.text||JSON.stringify(e.data),e)})})},async 'action.discord.send'(n,e){const c=await credential(event.projectId,n.data?.credentialId,'discord');if(!c)return;await fetch(c.webhookUrl,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({content:render(n.data?.text||JSON.stringify(e.data),e)})})},async 'action.email.send'(n,e){const c=await credential(event.projectId,n.data?.credentialId,'smtp');if(!c)return;const tr=nodemailer.createTransport({host:c.host,port:Number(c.port),secure:Boolean(c.secure),auth:{user:c.user,pass:c.pass}});await tr.sendMail({from:c.from||c.user,to:n.data?.to,subject:render(n.data?.subject||'IoTCloud alert',e),text:render(n.data?.text||JSON.stringify(e.data),e)})},async 'action.webhook.send'(n,e){if(!n.data?.url)return;await fetch(n.data.url,{method:n.data?.method||'POST',headers:{'content-type':'application/json',...(n.data?.headers||{})},body:JSON.stringify(e)})},async 'iot.mqtt.publish'(n,e){if(!n.data?.topic)return;const t= deviceTopic(e.projectId,n.data.deviceId||e.deviceId||'gateway',n.data.topic);broker.publish({cmd:'publish',topic:t,payload:Buffer.from(JSON.stringify(n.data.payload??e.data)),qos:0,retain:false,dup:false},()=>{})}});await pool.query('UPDATE workflow_runs SET status=$1,finished_at=now() WHERE id=$2',['success',run.rows[0].id])}catch(err){await pool.query('UPDATE workflow_runs SET status=$1,finished_at=now(),error=$2 WHERE id=$3',['error',String(err),run.rows[0].id]);app.log.error(err)}}}
function render(s:string,e:Event){return s.replace(/\\{\\{\\s*([^}]+)\\s*\\}\\}/g,(_,p)=>String(p.split('.').reduce((v:string|object,k:string)=>v&&typeof v==='object'?(v as any)[k]:undefined,e as any)??''))}
async function credential(projectId:string,id:string|undefined,kind:string){if(!id)return null;const {rows}=await pool.query('SELECT secret FROM credentials WHERE id=$1 AND project_id=$2 AND kind=$3',[id,projectId,kind]);if(!rows[0])return null;return JSON.parse(decrypt(rows[0].secret))}

broker.authenticate=async(client,username,password,cb)=>{try{const t=Buffer.isBuffer(username)?username.toString():String(username||'');const d=await deviceByToken(t);if(!d)return cb(null,false);(client as any).userdata=d;cb(null,true)}catch(e){cb(e as Error,false)}};
broker.authorizePublish=async(client,packet,cb)=>{const d=(client as any).userdata;if(!d||!allowedTopic(packet.topic,d.project_id,d.id))return cb(new Error('publish not authorized'));cb(null)};
broker.authorizeSubscribe=async(client,sub,cb)=>{const d=(client as any).userdata;const p=parseTopic(sub.topic);if(!d||!p||p.projectId!==d.project_id||p.deviceId!==d.id)return cb(new Error('subscribe not authorized'));cb(null,sub)};
broker.on('clientReady',async c=>{const d=(c as any).userdata;if(d){await pool.query('UPDATE devices SET online=true,last_seen=now() WHERE id=$1',[d.id]);emit(d.project_id,{id:crypto.randomUUID(),type:'device.online',deviceId:d.id,projectId:d.project_id,data:{},timestamp:new Date().toISOString()})}});
broker.on('clientDisconnect',async c=>{const d=(c as any).userdata;if(d){await pool.query('UPDATE devices SET online=false,last_seen=now() WHERE id=$1',[d.id]);emit(d.project_id,{id:crypto.randomUUID(),type:'device.offline',deviceId:d.id,projectId:d.project_id,data:{},timestamp:new Date().toISOString()})}});
broker.on('publish',async(packet,client)=>{if(!client||packet.topic.startsWith('$SYS'))return;const p=parseTopic(packet.topic);if(!p)return;let data:any;try{data=JSON.parse(packet.payload.toString())}catch{data={value:packet.payload.toString()}}const ev:Event={id:crypto.randomUUID(),type:'mqtt.message',topic:p.topic,deviceId:p.deviceId,projectId:p.projectId,data,timestamp:new Date().toISOString()};try{await pool.query('INSERT INTO telemetry(project_id,device_id,topic,payload) VALUES($1,$2,$3,$4)',[p.projectId,p.deviceId,p.topic,data]);await pool.query('UPDATE devices SET last_seen=now(),online=true WHERE id=$1',[p.deviceId])}catch(e){app.log.error(e)}emit(p.projectId,ev);runWorkflows(ev).catch(e=>app.log.error(e))});

app.addHook('onRequest',async(req,reply)=>{if(limited(req.ip))return reply.code(429).send({error:'rate limit exceeded'})});
const scheduleLast=new Map<string,number>();
setInterval(async()=>{try{const {rows}=await pool.query("SELECT id,project_id,definition FROM workflows WHERE enabled=true AND definition::text LIKE '%schedule.trigger%'");for(const w of rows){for(const n of (w.definition?.nodes||[])){if(n.type!=='schedule.trigger')continue;const sec=Math.max(5,Number(n.data?.intervalSeconds||60));const key=`${w.id}:${n.id}`;const now=Date.now();if(now-(scheduleLast.get(key)||0)>=sec*1000){scheduleLast.set(key,now);runWorkflows({id:crypto.randomUUID(),type:'schedule',projectId:w.project_id,data:{schedule:n.data||{}},timestamp:new Date().toISOString()}).catch(e=>app.log.error(e))}}}}catch(e){app.log.error(e)}},5000);

app.get('/health',async()=>({ok:true,service:'iotcloud',version:'1.0.0',time:new Date().toISOString()}));
app.decorate('auth',async(req:any,reply:any)=>{try{await req.jwtVerify()}catch{return reply.code(401).send({error:'unauthorized'})}});
app.post('/api/auth/register',async(req,rep)=>{const b=z.object({email:z.string().email(),password:z.string().min(8)}).parse(req.body);const hash=await bcrypt.hash(b.password,12);try{const {rows}=await pool.query('INSERT INTO users(email,password_hash) VALUES($1,$2) RETURNING id,email',[b.email.toLowerCase(),hash]);return {token:app.jwt.sign({sub:rows[0].id,email:rows[0].email}),user:rows[0]}}catch{return rep.code(409).send({error:'email already registered'})}});
app.post('/api/auth/login',async(req,rep)=>{const b=z.object({email:z.string().email(),password:z.string()}).parse(req.body);const {rows}=await pool.query('SELECT * FROM users WHERE email=$1',[b.email.toLowerCase()]);if(!rows[0]||!(await bcrypt.compare(b.password,rows[0].password_hash)))return rep.code(401).send({error:'invalid credentials'});return {token:app.jwt.sign({sub:rows[0].id,email:rows[0].email}),user:{id:rows[0].id,email:rows[0].email}}});
app.get('/api/me',{preHandler:(app as any).auth},async(req:any)=>({id:req.user.sub,email:req.user.email}));
app.get('/api/projects',{preHandler:(app as any).auth},async(req:any)=>{const {rows}=await pool.query('SELECT id,name,api_key,created_at FROM projects WHERE user_id=$1 ORDER BY created_at DESC',[req.user.sub]);return rows});
app.post('/api/projects',{preHandler:(app as any).auth},async(req:any)=>{const b=z.object({name:z.string().min(1).max(100)}).parse(req.body);const {rows}=await pool.query('INSERT INTO projects(user_id,name,api_key) VALUES($1,$2,$3) RETURNING id,name,api_key,created_at',[req.user.sub,b.name,token('pk')]);return rows[0]});
app.get('/api/projects/:id/devices',{preHandler:(app as any).auth},async(req:any,rep)=>{if(!await projectOwned(req.params.id,req.user.sub))return rep.code(404).send({error:'project not found'});const {rows}=await pool.query('SELECT id,name,token,metadata,last_seen,online,created_at FROM devices WHERE project_id=$1 ORDER BY created_at DESC',[req.params.id]);return rows});
app.post('/api/projects/:id/devices',{preHandler:(app as any).auth},async(req:any,rep)=>{if(!await projectOwned(req.params.id,req.user.sub))return rep.code(404).send({error:'project not found'});const b=z.object({name:z.string().min(1).max(100),metadata:z.record(z.string(), z.any()).optional()}).parse(req.body);const {rows}=await pool.query('INSERT INTO devices(project_id,name,token,metadata) VALUES($1,$2,$3,$4) RETURNING id,name,token,metadata',[req.params.id,b.name,token('dev'),b.metadata||{}]);return rows[0]});
app.delete('/api/projects/:id/devices/:deviceId',{preHandler:(app as any).auth},async(req:any,rep)=>{if(!await projectOwned(req.params.id,req.user.sub))return rep.code(404).send({error:'project not found'});await pool.query('DELETE FROM devices WHERE id=$1 AND project_id=$2',[req.params.deviceId,req.params.id]);return {ok:true}});
app.get('/api/projects/:id/telemetry',{preHandler:(app as any).auth},async(req:any,rep)=>{if(!await projectOwned(req.params.id,req.user.sub))return rep.code(404).send({error:'project not found'});const lim=Math.min(Number(req.query?.limit||100),500);const {rows}=await pool.query('SELECT id,device_id,topic,payload,created_at FROM telemetry WHERE project_id=$1 ORDER BY created_at DESC LIMIT $2',[req.params.id,lim]);return rows});
app.post('/api/device/publish',async(req:any,rep)=>{const b=z.object({deviceId:z.string().uuid(),topic:z.string().min(1),data:z.any()}).parse(req.body);const d=await deviceByToken(req.headers.authorization?.replace(/^Bearer /i,'')||'');if(!d||d.id!==b.deviceId)return rep.code(403).send({error:'device token required'});broker.publish({cmd:'publish',topic:deviceTopic(d.project_id,d.id,b.topic),payload:Buffer.from(JSON.stringify(b.data)),qos:0,retain:false,dup:false},()=>{});return {ok:true}});
app.get('/api/projects/:id/workflows',{preHandler:(app as any).auth},async(req:any,rep)=>{if(!await projectOwned(req.params.id,req.user.sub))return rep.code(404).send({error:'project not found'});const {rows}=await pool.query('SELECT id,name,definition,enabled,created_at,updated_at FROM workflows WHERE project_id=$1 ORDER BY updated_at DESC',[req.params.id]);return rows});
app.post('/api/projects/:id/workflows',{preHandler:(app as any).auth},async(req:any,rep)=>{if(!await projectOwned(req.params.id,req.user.sub))return rep.code(404).send({error:'project not found'});const b=z.object({name:z.string().min(1),definition:z.object({nodes:z.array(z.any()),edges:z.array(z.any())}),enabled:z.boolean().optional()}).parse(req.body);const definition={...b.definition,webhookSecret:token('wh')};const {rows}=await pool.query('INSERT INTO workflows(project_id,name,definition,enabled) VALUES($1,$2,$3,$4) RETURNING *',[req.params.id,b.name,definition,b.enabled??false]);return rows[0]});
app.put('/api/projects/:id/workflows/:workflowId',{preHandler:(app as any).auth},async(req:any,rep)=>{if(!await projectOwned(req.params.id,req.user.sub))return rep.code(404).send({error:'project not found'});const b=z.object({name:z.string().min(1).optional(),definition:z.object({nodes:z.array(z.any()),edges:z.array(z.any())}).optional(),enabled:z.boolean().optional()}).parse(req.body);const existing=await pool.query('SELECT definition FROM workflows WHERE id=$1 AND project_id=$2',[req.params.workflowId,req.params.id]);if(!existing.rows[0])return rep.code(404).send({error:'workflow not found'});const nextDef=b.definition?{...b.definition,webhookSecret:existing.rows[0].definition?.webhookSecret||token('wh')}:undefined;const {rows}=await pool.query('UPDATE workflows SET name=COALESCE($1,name),definition=COALESCE($2,definition),enabled=COALESCE($3,enabled),updated_at=now() WHERE id=$4 AND project_id=$5 RETURNING *',[b.name,nextDef,b.enabled,req.params.workflowId,req.params.id]);return rows[0]||rep.code(404).send({error:'workflow not found'})});
app.delete('/api/projects/:id/workflows/:workflowId',{preHandler:(app as any).auth},async(req:any,rep)=>{if(!await projectOwned(req.params.id,req.user.sub))return rep.code(404).send({error:'project not found'});await pool.query('DELETE FROM workflows WHERE id=$1 AND project_id=$2',[req.params.workflowId,req.params.id]);return {ok:true}});
app.get('/api/projects/:id/runs',{preHandler:(app as any).auth},async(req:any,rep)=>{if(!await projectOwned(req.params.id,req.user.sub))return rep.code(404).send({error:'project not found'});const {rows}=await pool.query('SELECT r.*,w.name workflow_name FROM workflow_runs r JOIN workflows w ON w.id=r.workflow_id WHERE w.project_id=$1 ORDER BY r.started_at DESC LIMIT 100',[req.params.id]);return rows});
app.post('/api/projects/:id/credentials',{preHandler:(app as any).auth},async(req:any,rep)=>{if(!await projectOwned(req.params.id,req.user.sub))return rep.code(404).send({error:'project not found'});const b=z.object({name:z.string().min(1),kind:z.enum(['telegram','discord','smtp','webhook']),config:z.record(z.string(), z.any())}).parse(req.body);const {rows}=await pool.query('INSERT INTO credentials(project_id,name,kind,secret) VALUES($1,$2,$3,$4) RETURNING id,name,kind,created_at',[req.params.id,b.name,b.kind,encrypt(JSON.stringify(b.config))]);return rows[0]});
app.get('/api/projects/:id/credentials',{preHandler:(app as any).auth},async(req:any,rep)=>{if(!await projectOwned(req.params.id,req.user.sub))return rep.code(404).send({error:'project not found'});const {rows}=await pool.query('SELECT id,name,kind,created_at FROM credentials WHERE project_id=$1 ORDER BY created_at DESC',[req.params.id]);return rows});
app.post('/api/projects/:id/credentials/:credentialId/test',{preHandler:(app as any).auth},async(req:any,rep)=>{if(!await projectOwned(req.params.id,req.user.sub))return rep.code(404).send({error:'project not found'});const {rows}=await pool.query('SELECT kind,secret FROM credentials WHERE id=$1 AND project_id=$2',[req.params.credentialId,req.params.id]);if(!rows[0])return rep.code(404).send({error:'credential not found'});const c=JSON.parse(decrypt(rows[0].secret));try{if(rows[0].kind==='discord')await fetch(c.webhookUrl,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({content:'IoTCloud connection test'})});else if(rows[0].kind==='telegram')await fetch(`https://api.telegram.org/bot${c.token}/getMe`);else if(rows[0].kind==='smtp'){const tr=nodemailer.createTransport({host:c.host,port:Number(c.port),secure:Boolean(c.secure),auth:{user:c.user,pass:c.pass}});await tr.verify()}else await fetch(c.url,{method:'HEAD'});return {ok:true}}catch(e){return rep.code(400).send({ok:false,error:String(e)})}});
app.post('/v1/webhooks/:workflowId',async(req:any,rep)=>{const {rows}=await pool.query('SELECT w.*,p.name project_name FROM workflows w JOIN projects p ON p.id=w.project_id WHERE w.id=$1 AND w.enabled=true',[req.params.workflowId]);if(!rows[0])return rep.code(404).send({error:'workflow not found'});const secret=String(req.headers['x-webhook-secret']||'');if(rows[0].definition?.webhookSecret && secret!==rows[0].definition.webhookSecret)return rep.code(401).send({error:'invalid webhook secret'});const e:Event={id:crypto.randomUUID(),type:'webhook',projectId:rows[0].project_id,data:req.body||{},timestamp:new Date().toISOString()};emit(e.projectId,e);await runWorkflows(e);return {ok:true,eventId:e.id}});
app.get('/api/docs',{preHandler:(app as any).auth},async(req:any)=>{const base=`${req.protocol}://${req.hostname}`;return {base,websocket:`${base.replace(/^http/,'ws')}/v1/ws?token=DEVICE_TOKEN`,sse:`${base}/v1/events?token=DEVICE_TOKEN`,mqttWebSocket:`${base.replace(/^http/,'ws')}/mqtt`,topics:'iotcloud/{projectId}/{deviceId}/{topic}',examples:{curl:`curl -X POST ${base}/api/device/publish -H 'Authorization: Bearer DEVICE_TOKEN' -H 'content-type: application/json' -d '{"deviceId":"DEVICE_ID","topic":"telemetry","data":{"temperature":28.4}}'`,javascript:`const ws=new WebSocket('${base.replace(/^http/,'ws')}/v1/ws?token=DEVICE_TOKEN'); ws.onmessage=e=>console.log(JSON.parse(e.data));`,python:`import requests\nrequests.post('${base}/api/device/publish',headers={'Authorization':'Bearer DEVICE_TOKEN'},json={'deviceId':'DEVICE_ID','topic':'telemetry','data':{'temperature':28.4}})`,esp32:`mqttClient.setServer("${req.hostname}",443); mqttClient.setCallback(callback); // use MQTT over WebSocket client library with TLS on your device`}}});
app.get('/v1/events',{preHandler:async(req:any,rep:any)=>{const d=await deviceByToken(String(req.query?.token||''));if(!d)return rep.code(401).send({error:'invalid token'});(req as any).device=d}},async(req:any,rep)=>{const d=(req as any).device;rep.raw.writeHead(200,{'content-type':'text/event-stream','cache-control':'no-cache, no-transform','connection':'keep-alive','access-control-allow-origin':'*'});rep.raw.write(`event: ready\\ndata: ${JSON.stringify({projectId:d.project_id,deviceId:d.id})}\\n\\n`);const set=sseClients.get(d.project_id)||new Set();set.add(rep);sseClients.set(d.project_id,set);const timer=setInterval(()=>rep.raw.write(': ping\\n\\n'),20000);req.raw.on('close',()=>{clearInterval(timer);set.delete(rep)});return rep});
app.get('/v1/ws',{websocket:true},(socket:any,req:any)=>{const tokenQ=new URL(req.url||'',`http://${req.headers.host}`).searchParams.get('token');let d:any;const p=deviceByToken(String(tokenQ||''));socket.on('message',async(raw:any)=>{try{const m=JSON.parse(raw.toString());d=d||await p;if(!d){socket.close(1008,'invalid token');return}if(m.action==='publish'){if(!m.topic)return;broker.publish({cmd:'publish',topic:deviceTopic(d.project_id,d.id,m.topic),payload:Buffer.from(JSON.stringify(m.data??{})),qos:0,retain:false,dup:false},()=>{})}else if(m.action==='subscribe'){socket.send(JSON.stringify({type:'info',message:'WebSocket is project event stream; use MQTT/WebSocket topic bridge for topic subscriptions'}))}}catch{socket.send(JSON.stringify({type:'error',error:'invalid message'}))}});p.then(x=>{d=x;if(!d){socket.close(1008,'invalid token');return}const set=wsClients.get(d.project_id)||new Set();set.add(socket);wsClients.set(d.project_id,set);socket.send(JSON.stringify({type:'ready',projectId:d.project_id,deviceId:d.id}));socket.on('close',()=>set.delete(socket))}).catch(()=>socket.close(1011))});
app.get('/mqtt',{websocket:true},(socket:any,req:any)=>{const stream=createWebSocketStream(socket, {});broker.handle(stream,req.raw)});

await migrate();
const mqttTcpPort=Number(process.env.MQTT_TCP_PORT||0);if(mqttTcpPort){createTcpServer(broker.handle).listen(mqttTcpPort,'0.0.0.0',()=>app.log.info(`MQTT TCP listening on ${mqttTcpPort}`))}
const port=Number(process.env.PORT||10000);await app.listen({port,host:'0.0.0.0'});app.log.info(`IoTCloud listening on ${port}`);
